//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accAfpslaiEmvObjct
{
    using System;
    using System.Collections.Generic;

    public partial class AddressList
    {
        public int ID { get; set; }
        public string CIF_NO { get; set; }
        public int PREFERRED_ADDRESS { get; set; }
        public string ADDRESS_TYPE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ADDRESS4 { get; set; }
        public string CITY { get; set; }
        public string ZIP_CODE { get; set; }
        public string STATE { get; set; }        
        public string COUNTRY { get; set; }
        public string FAX_CTY_CODE { get; set; }
        public string FAX_PREFIX { get; set; }
        public string FAX_NUMBER { get; set; }
        public string DISTRICT { get; set; }
        public string TOWN { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public string LAST_UPDATED_BRANCH { get; set; }
        public string LAST_APPROVED_BY { get; set; }
    }
}
