//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accAfpslaiEmvObjct
{
    using System;
    using System.Collections.Generic;

    public partial class cif_detail_search_response
    {
        public Header_Response Header { get; set; }
        public PersonalInfo PersonalInfo { get; set; }
        public List<HostMessage> HostMessages { get; set; }
        public HostReply HostReply { get; set; }       
    }
}
