//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accAfpslaiEmvObjct
{
    using System;
    using System.Collections.Generic;

    public partial class cif_detail_search_request
    {
        public string TranCode { get; set; }
        public string Salt { get; set; }
        public int SeqNo { get; set; }
        public Payload_Request Payload { get; set; }       
        public string Username { get; set; }
        public string Channel { get; set; }
    }
}
