//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accAfpslaiEmvObjct
{
    using System;
    using System.Collections.Generic;

    public partial class ContactList
    {
        public int ID { get; set; }
        public string CIF_NO { get; set; }
        public string CONTACT_TYPE { get; set; }
        public string CONTACT_VALUE { get; set; }
        public string MOBILE_CTY_CODE { get; set; }
        public string MOBILE_PREFIX { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public string PROVIDER { get; set; }
        public int PREFERRED_CONTACT { get; set; }
        public int E_COMMERCE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public string LAST_UPDATED_BRANCH { get; set; }
        public string LAST_APPROVED_BY { get; set; }
    }
}
