//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accAfpslaiEmvObjct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header_Response
    {
        public string Ticket { get; set; }
        public string TicketRefNo { get; set; }
        public Nullable<System.DateTime> BusinessDate { get; set; }      
        public string TranCode { get; set; }
        public string UserId { get; set; }
        public string ClientReference { get; set; }
        public string SequenceNo { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
        public int Status { get; set; }

    }
}
