//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accAfpslaiEmvObjct
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostMessage
    {
        public int Code { get; set; }
        public string Severity { get; set; }       
        public string Description { get; set; }       

    }
}
